<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "	<head> \n";
echo "		<link rel=\"stylesheet\" type=\"text/css\" href=\"adoptionstyle.css\">  	\n";
echo "		<title> ADOPT US </title> \n";
echo "	</head>\n";
echo "\n";
echo "<body style=\"background-image: linear-gradient(#5F6CAF,#FFB677); background-repeat: no-repeat;background-position:0px 300px; margin-bottom: 0px; border: 0px solid white;-moz-border-radius: 10px;\">\n";
echo "	\n";
echo "	\n";
echo "	\n";
echo "<div class=\"container\">\n";
echo " 	<img src=\"LOGO.png\" width=\"50\" height=\"50\" alt=\"LOGO\" class=\"logo\"/> \n";
echo " 		<h3 style=\"margin-right: 30px;\"> CARA Philippines Wellfare </h3>\n";
echo "		<div class=\"vl\"></div>\n";
echo "  \n";
echo "		<ul>\n";
echo "			<li><a href=\"index.html\">Home</a>         </li>\n";
echo "			<li> <a href=\"Join.html\">Join</a></li>\n";
echo "        	<li><a href=\"OurAnimals.html\">Our Animals</a> </li>\n";
echo "			<li><a href=\"AboutUs.html\">About Us</a>     </li>\n";
echo "			<li><a href=\"ContactUs.html\">Contact Us</a>   </li>\n";
echo "		</ul>\n";
echo "	</div>		\n";
echo "	\n";
echo "<div class=\"secondcontainer\">\n";
echo "	<img src=\"h1.png\" width=\"300\" height=\"400\" alt=\"h1\"style=\"margin-left: 10px;margin-top: 100px;\"/>\n";
echo "	\n";
echo "	<h1 style=\"margin-left: 30px; text-align: center;\"> ADOPT A PET\n";
echo "	\n";
echo "	<p> Is there a place in your heart and space <br>\n";
echo "	in your home for one of our delightful rescued pets?</p>\n";
echo "		\n";
echo "	<form action=\"Join.html\">	\n";
echo "		<button type=\"submit\" class=\"FirstButton\">GET STARTED</button>\n";
echo "	</form>\n";
echo "	</h1>\n";
echo "</div>\n";
echo "	\n";
echo "	\n";
echo "<center>\n";
echo "<div class=\"secondcontainer\">\n";
echo "	\n";
echo "	<div class=\"ccontainer\">\n";
echo " 		<img src=\"py.png\" alt=\"Avatar\" class=\"image\">\n";
echo "  		<div class=\"overlay\">\n";
echo "    		<div class=\"text\">Pet Adoption Policies</div>\n";
echo "  		</div>\n";
echo "	</div>\n";
echo "	\n";
echo "	<div class=\"ccontainer\">\n";
echo " 		<img src=\"benefit.png\" alt=\"Avatar\" class=\"image\">\n";
echo "  		<div class=\"overlay\">\n";
echo "    		<div class=\"text\">Pet Adoption Policies</div>\n";
echo "  		</div>\n";
echo "	</div>\n";
echo "	\n";
echo "	<div class=\"ccontainer\">\n";
echo " 		<img src=\"factor.png\" alt=\"Avatar\" class=\"image\">\n";
echo "  		<div class=\"overlay\">\n";
echo "    		<div class=\"text\">Pet Adoption Policies</div>\n";
echo "  		</div>\n";
echo "	</div>\n";
echo "	\n";
echo "</div>\n";
echo "	\n";
echo "<div class=\"bg\">\n";
echo "	\n";
echo "<div class=\"FourthBox\">\n";
echo "	\n";
echo "<p style=\"color: #FFB677;\"> We will make at least one follow up visit to ensure \n";
echo "that everybody is happy. CARA reserves the<br>\n";
echo "right to refuse adoption to any individual \n";
echo "who we feel is not suitable.</p>\n";
echo "</div>\n";
echo "	\n";
echo "<br><br>\n";
echo "	\n";
echo "<div class=\"hl\"></div>\n";
echo "	\n";
echo "<h6>© 2004- 2020 Adopt-a-Pet.com - All Rights Reserved</h6>	\n";
echo "	\n";
echo "</div>\n";
echo "	\n";
echo "</center>\n";
echo "\n";
echo "	\n";
echo "	\n";
echo "	\n";
echo "</body>\n";
echo "</html>";

?>
